apiVersion: apps/v1
kind: Deployment
metadata:
  name: debitcards
  labels:
    app: debitcards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debitcards
  template:
    metadata:
      labels:
        app: debitcards
    spec:
      containers:
        - name: debitcards
          image: "jagadeeshbackend/debit-card-ms:v1"
          ports:
            - containerPort : 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: DEBIT_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: DEBIT_DATASOURCE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: debitcards
spec:
  selector:
    app: debitcards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085