apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: jagadeeshbackend/eureka-server:v1
          ports:
            - containerPort : 8070
          env:
#            - SPRING_APPLICATION_NAME: "eureka"
#              EUREKA_INSTANCE_HOSTNAME: "eureka-server"
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: EUREKA_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: bank-configmap
                  key: EUREKA_INSTANCE_HOSTNAME

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070


