server:
  port: 8070
spring:
  application:
    name: "eurekaserver"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"